rm_django_app/main_app/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from . import views


app_name = "main_app"

urlpatterns = [
    path('', views.home, name='home'),
    url('signup/', views.signup, name='signup'),
    url('login/', views.login, name='login'), #Currenctly conflicts with default "login" added to urls
    url('authtestpage/', views.authtestpage, name="authtest"),
]

rm_django_app/rm_django_app/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main_app.urls', 'main_app'), namespace='main_app')),
    path('videos/', include(('videos.urls', 'videos'), namespace='videos')),

    # Include default django views for accounts. Need to add templates in registration
    path('accounts/', include('django.contrib.auth.urls')),
    # This provides the following default views:
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
]

rm_django_app/videos/urls.py
from django.urls import path

from . import views


app_name = 'videos'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('<int:video_id>/', views.viewvid, name='viewvid'),
    path('denied/', views.denied, name='denied'),
]

rm_django_app/main_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Client(AbstractUser):
    phone = models.CharField(max_length=10, null=True)
    partner_name = models.CharField(max_length=50, null=True)
    partner_phone = models.CharField(max_length=10, null=True)
    partner_email = models.CharField(max_length=50, null=True)
    address = models.CharField("street address", max_length=50, null=True)
    city = models.CharField(max_length=20, null=True)
    zip = models.CharField("zip code", max_length=9, null=True)
    state = models.CharField(max_length=2, null=True)
    due_date = models.DateField(null=True)

    def __str__(self):
        return self.username


class Provider(models.Model):
    name = models.CharField("Business name", max_length=50)
    contact = models.CharField("Contact person", max_length=30)
    email = models.CharField(max_length=50)
    phone = models.CharField("Phone number", max_length=10, )
    def __str__(self):
        return self.name


class Video(models.Model):
    title = models.CharField(max_length=35)
    link = models.CharField(max_length=100)
    embed_link = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.title

class Invoice(models.Model):
    amount = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    owing_client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)

rm_django_app/videos/models.py
from django.db import models

# Create your models here.

rm_django_app/main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Client


class SignUpForm(UserCreationForm):
    """
    A custom version of UserCreationForm
    Adds additional fields based on BoL's intake form
    """
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=100, help_text='Required. Inform a valid email address.')
    phone = forms.CharField(max_length=10, required=False, help_text='Enter your 10 digit phone number with no dashes or spaces')
    partner_name = forms.CharField(max_length=50, required=False, help_text='Enter your spouse/partner\'s name')
    partner_email = forms.CharField(max_length=50, required=False, help_text='Enter your spouse/partner\'s email')
    address = forms.CharField(max_length=50, required=False, help_text='Enter your street address')
    city = forms.CharField(max_length=50, required=False, help_text='Enter your city')
    state = forms.CharField(max_length=2, required=False, help_text='Enter your state abbreviation (i.e., \'FL\'')
    zip = forms.CharField(max_length=9, required=False, help_text='Enter your zip code')
    due_date = forms.DateField(required=False, help_text='Enter your due date')

    class Meta:
        model = Client
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'phone',
            'partner_name',
            'partner_email',
            'address',
            'city',
            'zip',
            'state',
            'due_date')

rm_django_app/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm


from .models import Client, Provider, Video, Invoice


# Create your views here.

def home(request):
    return render(request, 'home.html')


# Signup form for creating new users
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def login(request):
    form = AuthenticationForm
    return render(request, 'login.html', {'form': form})

def authtestpage(request):
    user = authenticate(username="testuser", password="testpassword")
    if user is not None:
        return HttpResponse("The user WAS authenticated")
    else:
        return HttpResponse("The user was not authenticated")

rm_django_app/videos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from main_app.models import Client, Video
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.

def index(request):
    video_list = Video.objects.all()
    context = {'video_list': video_list}
    return render(request, 'videos/index.html', context)

@login_required
@user_passes_test(lambda u: u.groups.filter(name='BoL_series').count() == 0, login_url='/login/', redirect_field_name="/videos/denied/")
def viewvid(request, video_id):
    video = Video.objects.get(pk=video_id)
    context = {'video_id': video_id, 'video': video}
    return render(request, 'videos/viewvid.html', context)

def denied(request):
    return render(request, 'videos/denied.html')

rm_django_app/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href= "{% static 'css/custom.css' %}">
    <link rel="stylesheet" href= "{% static 'css/footer.css' %}">
    <title>Redeemed Motherhood</title>
</head>

<body>

{% include 'header.html' %}


{% block content %}

{% endblock %}


</body>
</html>

rm_django_app/templates/footer.html
<div class="navbar navbar-default fixed-bottom">
    <div class="container">
        <div class="row bg-black text-white">
            <div class="col">column 1</div>
            <div class="col">column 2</div>
            <div class="col">column 3</div>
            <div class="col">column 4</div>
        </div>
    </div>
</div>


<!-- In progress. Not figured out. include in base.html to incorporate. -->

rm_django_app/templates/header.html
{% load static %}

<header>


  <div class="topbanner">
    <div class="container jumbotron">
      <h1 class="display-4">Redeemed Motherhood</h1>
      <p class="lead">Support and resources for new and expecting mothers</p>
      <hr class="my-4">
    </div>
  </div>

    <!-- If the navbar starts having issues, try removing it from row/col, or even the container.-->
    <div class="container">
      <div class="row">
        <div class="col">
          <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main_app:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About Redeemed Motherhood</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">All Courses</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'videos:index' %}">Video list</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

</header>

{% block content %}



{% endblock %} 

rm_django_app/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<h1>This text is in the home.html file.</h1>
<br>

<a href="{% url 'main_app:signup' %}" class="btn btn-primary">This will lead to the signup page. It uses a bootstrap primary button</a>

<button type="button" class="btn btn-secondary">This is a button that does nothing yet</button>

{% endblock %} 

rm_django_app/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<h1>The login.html file starts here.</h1>
<br>


<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <p>Welcome to Redeemed Mommyhood!</p>
            <p>If you don't yet have an account, please sign up here using the form below, or sign in using Facebook/Google</p>
        </div>



        <div class="col text-center">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                  <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  </p>
                {% endfor %}
                <button type="submit">Submit</button>
            </form>
        </div>


    </div>

<br>
    <div class="row">
        <div class="col"></div>
        <div class="col d-flex justify-content-center">
            <a href="{% url 'main_app:signup' %}" class="btn btn-primary">Create a new account</a>
        </div>
        <div class="col d-flex justify-content-center">
            <a href="#" class="btn btn-primary">Sign in using Facebook</a>
        </div>
        <div class="col"></div>
    </div>
</div>




{% endblock %} 

rm_django_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    
    <div class="col-12 text-center"><h2>Sign up</h2></div>

    <div class="col-md-3 leftbanner"></div>

    <div class="col-md-6">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                  <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              </p>
            {% endfor %}
            <button type="submit">Submit</button>
        </form>
    </div>

    <div class="col-md-3 rightbanner"></div>

  </div>
</div>

{% endblock %}

rm_django_app/videos/templates/videos/denied.html
{% extends 'base.html' %}


{% block content %}

<h1>You do not yet have permission to see this video.</h1>
<p>If you would like to view this video or series, please purchase the series</p>

{% endblock %} 

rm_django_app/videos/templates/videos/index.html
{% extends 'base.html' %}


{% block content %}
<h1>video index list</h1>

    <ul>
        {% for video in video_list %}
            <li><a href="../{{ video.id }}/">{{ video.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %} 

rm_django_app/videos/templates/videos/viewvid.html
<!--Django: Load static css from videos/static/videos-->
{% load static %}
<!DOCTYPE html>

{% block content %}

    <h1>
        This is a test and should display {{ video.title }} in an embedded video
    </h1>
    
    <!--Link to video-->
    <div id = video-box, class=video-box>
        <iframe width="560" height="315" src="{{ video.embed_link }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  
    </div>

    {% endblock %}